apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: b45z80i9g-java-quarkus
  janus-idp.io/tekton: b45z80i9g-java-quarkus
  backstage.io/kubernetes-id: b45z80i9g-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: b45z80i9g-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
